spring.application.name=git-blog-pipeline
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview
spring.ai.google.genai.api-key=${GENAI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GENAI_API_KEY}
logging.level.org.springframework.ai.chat.client.advisor=debug
spring.ai.vectorstore.pinecone.api-key=${PINECONE_API_KEY}
spring.ai.vectorstore.pinecone.namespace=default
spring.ai.vectorstore.pinecone.index-name=github
management.endpoints.web.exposure.include=sessions,metrics